name: FastPuppy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48164
title: FastPuppy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#194987'
    - '#bbcfea'
    - '#df3d3b'
    - '#000002'
    - '#fcfcf8'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
